name: Post AI Muse Tweets

on:
  # This section defines the scheduled runs using cron syntax (UTC times)
  schedule:
    # Runs at 8:00 AM EST (13:00 UTC)
    - cron: '0 13 * * *'
    # Runs at 8:00 PM EST (01:00 UTC next day)
    - cron: '0 1 * * *'
    # Runs at 11:00 PM EST (04:00 UTC next day)
    - cron: '0 4 * * *'

  # This allows you to manually trigger the workflow from the GitHub Actions tab
  workflow_dispatch:

jobs:
  post-tweets:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      # Use SUPABASE_ANON_KEY for the anon public key
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout repo
        # Update to v4 for the latest version
        uses: actions/checkout@v4

      - name: Set up Node.js
        # Update to v4 for the latest version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run daily post script
        # Removed the echo since it's already handled by npm run post output
        run: npm run post







