name: Manual AI Muse Tweet Push

on:
  # This section allows you to manually trigger the workflow from the GitHub Actions tab.
  # You'll see a "Run workflow" button.
  workflow_dispatch:

jobs:
  post-tweets:
    runs-on: ubuntu-latest
    env:
      # These are the environment variables your script needs to run.
      # They are securely fetched from your GitHub Repository Secrets.
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout repository
        # This step checks out your code from the repository.
        uses: actions/checkout@v4

      - name: Set up Node.js
        # Configures the Node.js environment needed for your script.
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Ensures compatibility with your project

      - name: Install dependencies
        # Installs all packages listed in your package.json (e.g., Supabase client, twitter-api-v2).
        run: npm ci

      - name: Run manual tweet post script
        # Executes your TypeScript cron script using ts-node.
        # This is the command that will attempt to post a tweet.
        run: npm run post







