name: Post AI Muse Tweets

on:
  schedule:
    # 8 AM EST = 12:00 UTC
    - cron: '0 12 * * *'
    # 8 PM EST = 00:00 UTC (next day UTC)
    - cron: '0 0 * * *'
    # 11 PM EST = 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  post-tweets:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run daily post script
        run: npm run post







