name: AIMuse Test Workflow

on:
  workflow_dispatch:   # Manual trigger for easy testing

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Show Supabase env vars
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL"
          echo "SUPABASE_KEY=$SUPABASE_KEY"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run posting script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run post
